-- =========================================================================================
-- MIGRACIÓN: ELECCIÓN DE ESPECIALISTA Y MODELO GEO MULTI-CAMPUS BUAP
-- Archivo : migration_specialist_choice.sql
-- Objetivo: Redefinir la asignación de especialistas para permitir que los estudiantes
--           elijan a sus psicólogos y nutriólogos desde Configuración.
--           Soporta múltiples campus BUAP (CU, CCU, CU2, regionales) con faculties,
--           buildings y geolocalización WGS-84 real.
-- Ejecución: Supabase SQL Editor
-- =========================================================================================

BEGIN;

-- =========================================================================================
-- 1. AMPLIACIÓN DE TABLAS DE CAMPUS Y FACULTADES
-- =========================================================================================

-- Tabla public.campuses: agregar columnas geográficas y configuración del mapa
ALTER TABLE public.campuses
  ADD COLUMN IF NOT EXISTS campus_code  TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS latitude     DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS longitude    DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS map_type     TEXT DEFAULT 'none' CHECK (map_type IN ('buap_virtual', 'google_maps', 'none')),
  ADD COLUMN IF NOT EXISTS map_config   JSONB DEFAULT '{}'::jsonb;

-- Tabla public.faculties: agregar columnas geográficas y servicios
ALTER TABLE public.faculties
  ADD COLUMN IF NOT EXISTS faculty_code TEXT,
  ADD COLUMN IF NOT EXISTS latitude     DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS longitude    DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS has_service  BOOLEAN DEFAULT FALSE;

-- =========================================================================================
-- 2. CREACIÓN DE LA TABLA DE EDIFICIOS (CATÁLOGO)
-- =========================================================================================

CREATE TABLE IF NOT EXISTS public.buildings (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id  BIGINT NOT NULL REFERENCES public.faculties(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  code        TEXT,
  latitude    DECIMAL(10,7),
  longitude   DECIMAL(10,7),
  created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Habilitar RLS en public.buildings
ALTER TABLE public.buildings ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para public.buildings
DROP POLICY IF EXISTS buildings_read ON public.buildings;
CREATE POLICY buildings_read ON public.buildings
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS buildings_admin_all ON public.buildings;
CREATE POLICY buildings_admin_all ON public.buildings
  FOR ALL TO authenticated USING (public.get_auth_role() = 1) WITH CHECK (public.get_auth_role() = 1);

-- =========================================================================================
-- 3. VINCULACIÓN EN AJUSTES DE PERSONAL DE LA SALUD
-- =========================================================================================

ALTER TABLE public.health_professional_settings
  ADD COLUMN IF NOT EXISTS building_id BIGINT REFERENCES public.buildings(id) ON DELETE SET NULL;

-- =========================================================================================
-- 4. POBLADO DE CAMPUS BUAP INICIALES
-- =========================================================================================

INSERT INTO public.campuses (name, campus_code, latitude, longitude, map_type, map_config) VALUES
  ('Ciudad Universitaria', 'CU', 19.0049000, -98.2023000, 'buap_virtual', '{"source":"recorridosvirtuales.buap.mx/mapa-cu"}'),
  ('Complejo Cultural Universitario', 'CCU', 19.0104000, -98.2435000, 'google_maps', '{}'),
  ('CU2 Ingenierías y Ciencias Naturales', 'CU2', 18.9669000, -98.1565000, 'google_maps', '{}'),
  ('Complejo Regional Centro', 'REG_CENTRO', 18.9867000, -97.9712000, 'none', '{}'),
  ('Complejo Regional Sur', 'REG_SUR', 18.4636000, -97.3912000, 'none', '{}'),
  ('Complejo Regional Norte', 'REG_NORTE', 20.2520000, -97.9620000, 'none', '{}'),
  ('Complejo Regional Nororiental', 'REG_NORORIENTAL', 19.8698000, -97.3620000, 'none', '{}'),
  ('Complejo Regional Mixteca', 'REG_MIXTECA', 18.6012000, -98.2612000, 'none', '{}')
ON CONFLICT (name) DO UPDATE SET
  campus_code = EXCLUDED.campus_code,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  map_type = EXCLUDED.map_type,
  map_config = EXCLUDED.map_config;

-- =========================================================================================
-- 5. FUNCIÓN RPC PARA OBTENER ESPECIALISTAS CON CALIFICACIÓN Y DISTANCIA
-- =========================================================================================

CREATE OR REPLACE FUNCTION public.get_specialists_for_student(
  p_student_id UUID,
  p_role_id    INTEGER   -- 3 = psicólogo, 4 = nutriólogo
)
RETURNS TABLE (
  id                  UUID,
  first_name          TEXT,
  last_name           TEXT,
  faculty_name        TEXT,
  faculty_code        TEXT,
  campus_name         TEXT,
  campus_code         TEXT,
  modality            TEXT,
  building_name       TEXT,
  office_room         TEXT,
  rating_avg          DECIMAL(3,2),
  total_evaluaciones  BIGINT,
  specialist_lat      DECIMAL(10,7),
  specialist_lng      DECIMAL(10,7),
  student_lat         DECIMAL(10,7),
  student_lng         DECIMAL(10,7),
  current_load        BIGINT,
  capacity            INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_student_faculty_id BIGINT;
BEGIN
  -- 1. Obtener la facultad del estudiante a partir de su perfil
  SELECT f.id INTO v_student_faculty_id
  FROM public.profiles p
  JOIN public.faculties f ON f.name ILIKE p.faculty
  WHERE p.user_id = p_student_id
  LIMIT 1;

  -- 2. Retornar la lista de especialistas activos del rol especificado
  RETURN QUERY
  SELECT
    u.id,
    pr.first_name,
    pr.last_name,
    f.name AS faculty_name,
    f.faculty_code,
    c.name AS campus_name,
    c.campus_code,
    hps.modality,
    COALESCE(b.name, hps.building) AS building_name,
    hps.office_room,
    COALESCE(ROUND(AVG(se.score_global)::numeric, 2)::DECIMAL(3,2), NULL) AS rating_avg,
    COUNT(se.id)::BIGINT AS total_evaluaciones,
    COALESCE(b.latitude, f.latitude) AS specialist_lat,
    COALESCE(b.longitude, f.longitude) AS specialist_lng,
    sf.latitude AS student_lat,
    sf.longitude AS student_lng,
    (
      SELECT COUNT(*)
      FROM public.student_clinical_records scr
      WHERE (p_role_id = 3 AND scr.primary_psychologist_id = u.id)
         OR (p_role_id = 4 AND scr.primary_nutritionist_id = u.id)
    )::BIGINT AS current_load,
    hps.capacity
  FROM public.users u
  JOIN public.profiles pr ON pr.user_id = u.id
  JOIN public.health_professional_settings hps ON hps.professional_id = u.id
  LEFT JOIN public.faculties f ON f.id = hps.faculty_id
  LEFT JOIN public.campuses c ON c.id = f.campus_id
  LEFT JOIN public.buildings b ON b.id = hps.building_id
  LEFT JOIN public.faculties sf ON sf.id = v_student_faculty_id
  LEFT JOIN public.session_evaluations se ON se.professional_id = u.id
  WHERE u.role_id = p_role_id
    AND u.is_active = TRUE
    AND hps.faculty_id IS NOT NULL  -- Se requiere que tengan una facultad asignada
  GROUP BY
    u.id,
    pr.first_name,
    pr.last_name,
    f.name,
    f.faculty_code,
    f.latitude,
    f.longitude,
    c.name,
    c.campus_code,
    hps.modality,
    hps.building,
    hps.office_room,
    hps.capacity,
    b.name,
    b.latitude,
    b.longitude,
    sf.latitude,
    sf.longitude;
END;
$$;

-- =========================================================================================
-- 6. NOTIFICAR A POSTGREST PARA RECARGA DEL ESQUEMA
-- =========================================================================================
NOTIFY pgrst, 'reload schema';

COMMIT;
