-- =========================================================================================
-- EXTENSIONES
-- =========================================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================================
-- ROLES
-- =========================================================================================
CREATE TABLE public.roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO public.roles (id, name) VALUES 
  (1, 'Admin'),
  (2, 'Estudiante'),
  (3, 'Psicologo'),
  (4, 'Nutricionista')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

SELECT setval('public.roles_id_seq', 4, true);

-- =========================================================================================
-- USUARIOS
-- =========================================================================================
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    matricula VARCHAR(50) UNIQUE NOT NULL,
    role_id INTEGER REFERENCES public.roles(id) ON DELETE SET NULL,
    mobile_phone VARCHAR(20),
    whatsapp_opt_in BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- PERFILES
-- =========================================================================================

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    faculty TEXT,
    programa_educativo TEXT,
    celular VARCHAR(15),
    antecedentes_familiares TEXT,
    sexo VARCHAR(20),
    fecha_nacimiento DATE,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id)
);

-- =========================================================================================
-- CAMPUS Y FACULTADES (RECORRIDOS VIRTUALES Y UBICACIÓN)
-- =========================================================================================

CREATE TABLE public.campuses (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.faculties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id INTEGER REFERENCES public.campuses(id) ON DELETE CASCADE,
    name TEXT NOT NULL UNIQUE,
    virtual_tour_url TEXT, -- Enlace al recorrido virtual 360 (Planta Física BUAP)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================================
-- EXPEDIENTES CLÍNICOS Y CONFIGURACIONES
-- =========================================================================================

CREATE TABLE public.student_clinical_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    primary_psychologist_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    primary_nutritionist_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    known_conditions TEXT[] DEFAULT '{}',
    consent_given BOOLEAN DEFAULT FALSE,
    additional_notes TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id)
);

CREATE TABLE public.patient_settings (
    student_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'active',
    self_diagnosis VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- CHAT AMATI (ASISTENTE IA) - ALTA SEGURIDAD
-- =========================================================================================

CREATE TABLE public.chats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT,
    status VARCHAR(20) DEFAULT 'active',
    highest_urgency_score DECIMAL(3,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    chat_id UUID REFERENCES public.chats(id) ON DELETE CASCADE,
    sender_type VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    urgency_score DECIMAL(3,2),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- AGENDA Y AJUSTES CLÍNICOS
-- =========================================================================================

CREATE TABLE public.appointments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    professional_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    scheduled_date TIMESTAMP NOT NULL,
    start_time TIME,
    end_time TIME,
    priority_level VARCHAR(20) DEFAULT 'Routine',
    status VARCHAR(20) DEFAULT 'scheduled',
    cancellation_reason TEXT,
    notes TEXT,
    dual_notification_status VARCHAR(50) DEFAULT 'pending',
    emergency_change_type VARCHAR(50),
    emergency_change_details TEXT,
    cancellation_notified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.health_professional_settings (
    professional_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    session_duration INTEGER DEFAULT 50,
    capacity INTEGER DEFAULT 35,
    location TEXT DEFAULT 'Consultorio Virtual',
    modality TEXT DEFAULT 'virtual', -- 'virtual' o 'presencial'
    faculty_id BIGINT REFERENCES public.faculties(id) ON DELETE SET NULL, -- Facultad donde atiende
    building TEXT, -- Edificio (ej. EMA1, Edificio Arronte)
    office_room TEXT, -- Aula u Oficina (ej. Consultorio 3, Cubículo 102)
    working_days JSONB DEFAULT '{}', -- Ejemplo: {"monday": {"start": "09:00", "end": "17:00"}}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.health_professional_exceptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    professional_id UUID REFERENCES public.users(id),
    exception_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- NUTRICIÓN
-- =========================================================================================
CREATE TABLE public.campos_formulario (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bloque TEXT NOT NULL,
    clave TEXT NOT NULL UNIQUE,
    etiqueta TEXT NOT NULL,
    tipo_campo TEXT NOT NULL CHECK (tipo_campo IN ('text', 'number', 'boolean', 'select', 'rich-text', 'food-table')),
    orden INTEGER NOT NULL DEFAULT 0,
    ayuda TEXT,
    opciones JSONB NOT NULL DEFAULT '[]'::jsonb,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.consultas_nutricion (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    professional_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL,
    fecha_consulta TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    calorias_totales INTEGER NOT NULL DEFAULT 0 CHECK (calorias_totales >= 0),
    datos_especificos JSONB NOT NULL DEFAULT '{}'::jsonb,
    consumo_semanal JSONB NOT NULL DEFAULT '{}'::jsonb,
    recordatorio_24h JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.nutrition_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    log_date DATE DEFAULT CURRENT_DATE,
    total_calories INTEGER DEFAULT 0,
    total_protein DECIMAL(5,2) DEFAULT 0,
    total_carbs DECIMAL(5,2) DEFAULT 0,
    total_fats DECIMAL(5,2) DEFAULT 0,
    UNIQUE(student_id, log_date)
);

CREATE TABLE public.food_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nutrition_log_id UUID REFERENCES public.nutrition_logs(id) ON DELETE CASCADE,
    meal_type VARCHAR(50),
    name TEXT,
    calories INTEGER,
    protein DECIMAL(5,2),
    carbs DECIMAL(5,2),
    fats DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO public.campos_formulario (bloque, clave, etiqueta, tipo_campo, orden, ayuda, opciones, activo)
VALUES
    ('Datos específicos', 'problemas_gastrointestinales', 'Problemas gastrointestinales', 'text', 10, 'Dolor, reflujo, estreñimiento u otros malestares digestivos.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'alergia_intolerancia', 'Alergias o intolerancias', 'text', 20, 'Alergias alimentarias o intolerancias relevantes.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'enfermedad_padecimiento', 'Enfermedad o padecimiento', 'text', 30, 'Condición clínica que impacta la alimentación.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'medicamentos_consumo', 'Medicamentos en consumo', 'text', 40, 'Medicamentos o suplementos actuales.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'alimentos_desagrado', 'Alimentos de desagrado', 'text', 50, 'Alimentos que el paciente evita.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'actividad_fisica', 'Actividad física', 'text', 60, 'Tipo de actividad física habitual.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'dias_actividad', 'Días de actividad por semana', 'number', 70, 'Número de días con actividad física semanal.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'tiempo_actividad', 'Tiempo de actividad por día (min)', 'number', 80, 'Minutos aproximados por sesión.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'comidas_al_dia', 'Comidas al día', 'number', 90, 'Número de comidas principales.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'colaciones_al_dia', 'Colaciones al día', 'number', 100, 'Número de colaciones.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'comidas_mantener', 'Comidas que desea mantener', 'text', 110, 'Hábitos o platillos que quiere conservar.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'consumo_agua', 'Consumo de agua (L)', 'number', 120, 'Litros de agua al día o promedio.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'tiempo_sueno', 'Tiempo de sueño (hrs)', 'number', 130, 'Horas promedio de sueño por noche.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'antecedentes_familiares', 'Antecedentes Clínicos Familiares', 'rich-text', 135, 'Antecedentes clínicos familiares.', '[]'::jsonb, TRUE),
    ('Datos específicos', 'comentarios_clinicos', 'Comentarios clínicos', 'rich-text', 140, 'Observaciones libres del nutriólogo.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'verduras', 'Verduras', 'food-table', 210, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'frutas', 'Frutas', 'food-table', 220, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'lacteos', 'Lácteos', 'food-table', 230, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'cereales', 'Cereales', 'food-table', 240, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'leguminosas', 'Leguminosas', 'food-table', 250, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'azucar', 'Azúcar', 'food-table', 260, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'aoa', 'AOA', 'food-table', 270, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'aceites', 'Aceites y grasas', 'food-table', 280, 'Registro de consumo semanal.', '[]'::jsonb, TRUE),
    ('Consumo semanal', 'comentarios_semanales', 'Comentarios semanales', 'rich-text', 290, 'Observaciones sobre la frecuencia alimentaria.', '[]'::jsonb, TRUE)
ON CONFLICT (clave) DO UPDATE
SET bloque = EXCLUDED.bloque,
    etiqueta = EXCLUDED.etiqueta,
    tipo_campo = EXCLUDED.tipo_campo,
    orden = EXCLUDED.orden,
    ayuda = EXCLUDED.ayuda,
    opciones = EXCLUDED.opciones,
    activo = EXCLUDED.activo;

-- =========================================================================================
-- DIARIO EMOCIONAL
-- =========================================================================================
CREATE TABLE public.diary_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    content TEXT,
    moods TEXT[],
    high_risk BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- DIARIO ALIMENTARIO PERSONAL (Automonitoreo emocional-nutricional del estudiante)
-- Tabla separada de nutrition_logs (módulo clínico del nutriólogo con macros calculados).
-- Esta tabla registra la experiencia subjetiva del estudiante: hora de comida,
-- estado emocional antes/después y descripción libre de lo consumido.
-- =========================================================================================
CREATE TABLE public.food_diary_entries (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id  UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    diary_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    meal_time   TIME NOT NULL,
    mood_before TEXT NOT NULL,
    what_i_ate  TEXT NOT NULL,   -- Texto enriquecido (HTML de Quill)
    mood_after  TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.food_diary_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "food_diary_access"
    ON public.food_diary_entries
    FOR ALL
    TO authenticated
    USING (
        student_id = auth.uid()
        OR public.get_auth_role() IN (1, 3, 4)
    )
    WITH CHECK (
        student_id = auth.uid()
        OR public.get_auth_role() = 1
    );

CREATE INDEX idx_food_diary_student_date
    ON public.food_diary_entries(student_id, diary_date DESC);

-- =========================================================================================
-- COMUNICACIÓN DUAL Y ENRUTAMIENTO BIDIRECCIONAL (WEB PUSH & WHATSAPP)
-- =========================================================================================

CREATE TABLE public.web_push_subscriptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.whatsapp_routing_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    appointment_id UUID REFERENCES public.appointments(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    professional_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    session_status VARCHAR(50) DEFAULT 'active', -- 'active', 'closed', 'expired'
    whatsapp_thread_id TEXT,
    last_message_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- BITÁCORA DE AUDITORÍA (AUDIT LOGS - NOM-024 / HIPAA)
-- =========================================================================================

CREATE TABLE public.audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    event_type VARCHAR(50) NOT NULL, -- 'UNAUTHORIZED_ACCESS', 'LOGIN_FAILED', 'SESSION_TIMEOUT' (15 mins inactividad / cierre de pestaña)
    description TEXT NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- FUNCIÓN DE ROL (SEGURA)
-- =========================================================================================
CREATE OR REPLACE FUNCTION public.get_auth_role()
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT COALESCE(
    (SELECT role_id FROM public.users WHERE id = auth.uid()),
    0
  );
$$;

-- Función RPC Segura para que el Admin (Jefatura) consulte psicólogos y correos de auth.users
-- Elimina por completo la necesidad de guardar el correo en public.profiles
CREATE OR REPLACE FUNCTION public.get_admin_psychologists()
RETURNS TABLE (
    id UUID,
    role_id INTEGER,
    matricula VARCHAR,
    first_name TEXT,
    last_name TEXT,
    faculty TEXT,
    email VARCHAR,
    capacity INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER -- Ejecuta con privilegios del creador (acceso a auth.users)
AS $$
BEGIN
    -- Validar que el usuario que ejecuta sea Admin (role_id = 1)
    IF public.get_auth_role() != 1 THEN
        RAISE EXCEPTION 'Acceso denegado. Solo la Jefatura de Psicología (Admin) puede consultar esta información.';
    END IF;

    RETURN QUERY
    SELECT 
        u.id,
        u.role_id,
        u.matricula,
        p.first_name,
        p.last_name,
        p.faculty,
        a.email::VARCHAR,
        s.capacity
    FROM public.users u
    JOIN auth.users a ON u.id = a.id
    LEFT JOIN public.profiles p ON u.id = p.user_id
    LEFT JOIN public.health_professional_settings s ON u.id = s.professional_id
    WHERE u.role_id = 3;
END;
$$;

-- =========================================================================================
-- RLS (ROW LEVEL SECURITY)
-- =========================================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_clinical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campos_formulario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultas_nutricion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diary_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_professional_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_professional_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.web_push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_routing_sessions ENABLE ROW LEVEL SECURITY;

-- Política de Usuarios: Un usuario solo puede ver y editar su propia data pública
CREATE POLICY user_own_data ON public.users FOR ALL USING (id = auth.uid());
CREATE POLICY profile_own_data ON public.profiles FOR ALL USING (user_id = auth.uid());

-- Políticas para Administrador (Jefatura / Skill 8 - HIPAA Minimum Necessary & NOM-024):
-- 1. El Admin puede ver el directorio de pacientes (estudiantes, role_id = 2) y ver/gestionar personal médico (role_id IN (3, 4))
CREATE POLICY admin_manage_users ON public.users FOR ALL USING (
    public.get_auth_role() = 1
) WITH CHECK (
    public.get_auth_role() = 1
);

CREATE POLICY admin_manage_profiles ON public.profiles FOR ALL USING (
    public.get_auth_role() = 1
) WITH CHECK (
    public.get_auth_role() = 1
);

-- Nota Normativa HIPAA Minimum Necessary & NOM-024:
-- El acceso al módulo nutricional queda limitado a Nutriólogo, paciente propietario y Admin.
-- Las tablas student_clinical_records, chats, messages y diary_entries siguen sin políticas de lectura para Admin.

-- Nutrición: catálogo de campos solo para Admin y Nutriólogo
CREATE POLICY campos_formulario_select ON public.campos_formulario
    FOR SELECT USING (public.get_auth_role() IN (1, 4));

CREATE POLICY campos_formulario_admin_all ON public.campos_formulario
    FOR ALL USING (public.get_auth_role() = 1)
    WITH CHECK (public.get_auth_role() = 1);

-- Nutrición: consultas inmutables, visibles para paciente, nutriólogo y admin
CREATE POLICY consultas_nutricion_select ON public.consultas_nutricion
    FOR SELECT USING (
        student_id = auth.uid()
        OR professional_id = auth.uid()
        OR public.get_auth_role() = 1
    );

CREATE POLICY consultas_nutricion_insert ON public.consultas_nutricion
    FOR INSERT WITH CHECK (
        professional_id = auth.uid()
        OR public.get_auth_role() = 1
    );

CREATE POLICY consultas_nutricion_admin_all ON public.consultas_nutricion
    FOR ALL USING (public.get_auth_role() = 1)
    WITH CHECK (public.get_auth_role() = 1);

CREATE INDEX idx_campos_formulario_bloque_activo ON public.campos_formulario (bloque, activo, orden);
CREATE INDEX idx_consultas_nutricion_student_fecha ON public.consultas_nutricion (student_id, fecha_consulta DESC);
CREATE INDEX idx_consultas_nutricion_professional_fecha ON public.consultas_nutricion (professional_id, fecha_consulta DESC);
CREATE UNIQUE INDEX uq_consultas_nutricion_appointment_id ON public.consultas_nutricion (appointment_id) WHERE appointment_id IS NOT NULL;

-- Política de Auditoría: Solo inserción pública autenticada, solo lectura para Admin (Jefatura)
CREATE POLICY audit_insert ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY audit_select ON public.audit_logs FOR SELECT TO authenticated USING (
    public.get_auth_role() = 1
);

-- Política de Chats: El estudiante solo ve sus chats (Los psicólogos leerán mediante backend seguro)
CREATE POLICY chat_own_data ON public.chats FOR ALL USING (student_id = auth.uid());
CREATE POLICY message_own_data ON public.messages FOR ALL USING (
    EXISTS (SELECT 1 FROM public.chats c WHERE c.id = chat_id AND c.student_id = auth.uid())
);

-- Diario
CREATE POLICY "diary_access"
    ON public.diary_entries
    FOR ALL
    TO authenticated
    USING (
        student_id = auth.uid()
        OR public.get_auth_role() IN (1, 3, 4)
    )
    WITH CHECK (
        student_id = auth.uid()
        OR public.get_auth_role() = 1
    );

-- Políticas para Personal de la Salud (Psicólogos y Nutricionistas):
-- 1. El personal de la salud puede ver la tabla pública de usuarios si estos son estudiantes (role_id = 2)
CREATE POLICY health_prof_read_users ON public.users FOR SELECT USING (
    public.get_auth_role() IN (3, 4) AND role_id = 2
);

CREATE POLICY health_prof_read_profiles ON public.profiles FOR SELECT USING (
    public.get_auth_role() IN (3, 4)
);

CREATE POLICY health_prof_access_records ON public.student_clinical_records FOR ALL USING (
    public.get_auth_role() IN (3, 4)
) WITH CHECK (
    public.get_auth_role() IN (3, 4)
);

-- Políticas para Configuración y Citas del Personal de la Salud (Psicólogos y Nutricionistas)
CREATE POLICY health_prof_settings_own ON public.health_professional_settings
    FOR ALL USING (professional_id = auth.uid()) WITH CHECK (professional_id = auth.uid());

CREATE POLICY health_prof_settings_read ON public.health_professional_settings
    FOR SELECT USING (true);

CREATE POLICY health_prof_exceptions_own ON public.health_professional_exceptions
    FOR ALL USING (professional_id = auth.uid()) WITH CHECK (professional_id = auth.uid());

CREATE POLICY health_prof_exceptions_read ON public.health_professional_exceptions
    FOR SELECT USING (true);

CREATE POLICY admin_global_exceptions ON public.health_professional_exceptions
    FOR ALL USING (public.get_auth_role() = 1);

CREATE POLICY appointments_own_data ON public.appointments
    FOR ALL USING (student_id = auth.uid() OR professional_id = auth.uid())
    WITH CHECK (student_id = auth.uid() OR professional_id = auth.uid());

CREATE POLICY "Personal de la salud y admin pueden editar citas" ON public.appointments
    FOR UPDATE TO public USING (public.get_auth_role() IN (1, 3, 4));

-- Web push subscription policies
CREATE POLICY web_push_subs_own ON public.web_push_subscriptions
    FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY health_prof_read_web_push ON public.web_push_subscriptions
    FOR SELECT USING (public.get_auth_role() IN (3, 4));

-- WhatsApp routing session policies
CREATE POLICY whatsapp_sessions_own ON public.whatsapp_routing_sessions
    FOR ALL USING (student_id = auth.uid() OR professional_id = auth.uid())
    WITH CHECK (student_id = auth.uid() OR professional_id = auth.uid());


-- =========================================================================================
-- ÍNDICES
-- =========================================================================================
CREATE INDEX idx_chats_student ON public.chats(student_id);
CREATE INDEX idx_messages_chat ON public.messages(chat_id);
CREATE INDEX idx_appointments_professional ON public.appointments(professional_id);
CREATE INDEX idx_diary_student ON public.diary_entries(student_id);
CREATE INDEX idx_nutrition_logs ON public.nutrition_logs(student_id, log_date);
CREATE INDEX idx_web_push_user ON public.web_push_subscriptions(user_id);
CREATE INDEX idx_whatsapp_sessions_student ON public.whatsapp_routing_sessions(student_id);
CREATE INDEX idx_whatsapp_sessions_professional ON public.whatsapp_routing_sessions(professional_id);
CREATE INDEX idx_whatsapp_sessions_appointment ON public.whatsapp_routing_sessions(appointment_id);

-- =========================================================================================
-- SUPABASE DATABASE WEBHOOKS (EDGE FUNCTIONS TRIGGER)
-- =========================================================================================

-- Definición conceptual e instruccional del Webhook en Supabase
-- (En Supabase, los Webhooks se configuran nativamente en Dashboard -> Database -> Webhooks)
-- Configuración a habilitar en consola:
-- 1. Tabla: appointments
-- 2. Evento: UPDATE
-- 3. Condición de filtro: emergency_change_type IS NOT NULL
-- 4. Método HTTP: POST
-- 5. URL de destino: https://<project_ref>.supabase.co/functions/v1/emergency-web-push
-- 6. Cabecera HTTP: Authorization: Bearer <SUPABASE_ANON_KEY>

-- Disparador nativo de PostgreSQL (respaldo para invocación vía pg_net / http si está disponible)
CREATE OR REPLACE FUNCTION public.trg_emergency_push_notification()
RETURNS TRIGGER AS $$
BEGIN
  -- Si el estado de emergencia fue actualizado, el motor de webhooks capturará este cambio
  -- para disparar el paquete VAPID a través de la Edge Function en Deno.
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_emergency_push_notification ON public.appointments;
CREATE TRIGGER trigger_emergency_push_notification
  AFTER UPDATE OF emergency_change_type ON public.appointments
  FOR EACH ROW
  WHEN (NEW.emergency_change_type IS NOT NULL AND OLD.emergency_change_type IS DISTINCT FROM NEW.emergency_change_type)
  EXECUTE FUNCTION public.trg_emergency_push_notification();


-- =========================================================================================
-- MÓDULO DE ADMINISTRACIÓN: FUNCIONES SEGURAS Y ALTA CENTRALIZADA (SKILL 8.1)
-- =========================================================================================

CREATE OR REPLACE FUNCTION public.admin_register_health_professional(
    p_user_id UUID,
    p_matricula TEXT,
    p_role_id INTEGER,
    p_first_name TEXT,
    p_last_name TEXT,
    p_faculty TEXT,
    p_programa_educativo TEXT,
    p_celular TEXT,
    p_capacity INTEGER,
    p_location TEXT,
    p_modality TEXT,
    p_faculty_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_role_name TEXT;
    v_result JSONB;
BEGIN
    IF public.get_auth_role() != 1 THEN
        RAISE EXCEPTION 'CRITICAL_SECURITY_ERR: Acceso denegado. Solo la Jefatura (Admin) está autorizada para registrar personal de la salud.';
    END IF;

    IF p_role_id NOT IN (3, 4) THEN
        RAISE EXCEPTION 'VALIDATION_ERR: El rol especificado (%) no es válido para personal de la salud. Use 3 (Psicólogo) o 4 (Nutriólogo).', p_role_id;
    END IF;

    SELECT name INTO v_role_name FROM public.roles WHERE id = p_role_id;

    INSERT INTO public.users (id, matricula, role_id, mobile_phone, whatsapp_opt_in, created_at)
    VALUES (p_user_id, p_matricula, p_role_id, p_celular, TRUE, NOW())
    ON CONFLICT (id) DO UPDATE 
    SET matricula = EXCLUDED.matricula,
        role_id = EXCLUDED.role_id,
        mobile_phone = EXCLUDED.mobile_phone;

    INSERT INTO public.profiles (user_id, first_name, last_name, faculty, programa_educativo, celular, created_at)
    VALUES (p_user_id, p_first_name, p_last_name, p_faculty, p_programa_educativo, p_celular, NOW())
    ON CONFLICT (user_id) DO UPDATE
    SET first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        faculty = EXCLUDED.faculty,
        programa_educativo = EXCLUDED.programa_educativo,
        celular = EXCLUDED.celular;

    INSERT INTO public.health_professional_settings (professional_id, capacity, location, modality, faculty_id, updated_at)
    VALUES (p_user_id, p_capacity, p_location, p_modality, p_faculty_id, NOW())
    ON CONFLICT (professional_id) DO UPDATE
    SET capacity = EXCLUDED.capacity,
        location = EXCLUDED.location,
        modality = EXCLUDED.modality,
        faculty_id = EXCLUDED.faculty_id,
        updated_at = NOW();

    INSERT INTO public.audit_logs (user_id, event_type, description, ip_address, created_at)
    VALUES (
        auth.uid(), 
        'ADMIN_REGISTER_PROFESSIONAL', 
        FORMAT('Registro centralizado exitoso de %s: %s %s (Matrícula: %s, ID: %s)', v_role_name, p_first_name, p_last_name, p_matricula, p_user_id),
        coalesce(current_setting('request.headers', true)::jsonb->>'x-forwarded-for', 'local'),
        NOW()
    );

    v_result := jsonb_build_object(
        'success', true,
        'user_id', p_user_id,
        'matricula', p_matricula,
        'role_id', p_role_id,
        'role_name', v_role_name,
        'message', FORMAT('El %s ha sido registrado exitosamente en el sistema.', v_role_name)
    );

    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_health_professionals()
RETURNS TABLE (
    id UUID,
    role_id INTEGER,
    role_name VARCHAR,
    matricula VARCHAR,
    first_name TEXT,
    last_name TEXT,
    faculty TEXT,
    email VARCHAR,
    capacity INTEGER,
    location TEXT,
    modality TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF public.get_auth_role() != 1 THEN
        RAISE EXCEPTION 'Acceso denegado. Solo la Jefatura (Admin) puede consultar el directorio completo de profesionales de la salud.';
    END IF;

    RETURN QUERY
    SELECT 
        u.id,
        u.role_id,
        r.name::VARCHAR AS role_name,
        u.matricula,
        p.first_name,
        p.last_name,
        p.faculty,
        a.email::VARCHAR,
        s.capacity,
        s.location,
        s.modality
    FROM public.users u
    JOIN auth.users a ON u.id = a.id
    JOIN public.roles r ON u.role_id = r.id
    LEFT JOIN public.profiles p ON u.id = p.user_id
    LEFT JOIN public.health_professional_settings s ON u.id = s.professional_id
    WHERE u.role_id IN (3, 4)
    ORDER BY u.role_id ASC, p.last_name ASC;
END;
$$;


-- =========================================================================================
-- LÓGICA DE ASIGNACIÓN DE PACIENTES (SKILL 8.2)
-- =========================================================================================

CREATE OR REPLACE FUNCTION public.admin_assign_patient_to_professionals(
    p_student_id UUID,
    p_primary_psychologist_id UUID DEFAULT NULL,
    p_primary_nutritionist_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_student_exists BOOLEAN;
    v_psy_valid BOOLEAN := TRUE;
    v_nut_valid BOOLEAN := TRUE;
    v_result JSONB;
BEGIN
    IF public.get_auth_role() != 1 THEN
        RAISE EXCEPTION 'CRITICAL_SECURITY_ERR: Acceso denegado. Solo la Jefatura (Admin) puede asignar o reasignar pacientes.';
    END IF;

    SELECT EXISTS(SELECT 1 FROM public.users WHERE id = p_student_id AND role_id = 2) INTO v_student_exists;
    IF NOT v_student_exists THEN
        RAISE EXCEPTION 'VALIDATION_ERR: El estudiante especificado no existe o no tiene el rol de Estudiante (role_id = 2).';
    END IF;

    IF p_primary_psychologist_id IS NOT NULL THEN
        SELECT EXISTS(SELECT 1 FROM public.users WHERE id = p_primary_psychologist_id AND role_id = 3) INTO v_psy_valid;
        IF NOT v_psy_valid THEN
            RAISE EXCEPTION 'VALIDATION_ERR: El usuario asignado como psicólogo primario no existe o no tiene el rol de Psicólogo (role_id = 3).';
        END IF;
    END IF;

    IF p_primary_nutritionist_id IS NOT NULL THEN
        SELECT EXISTS(SELECT 1 FROM public.users WHERE id = p_primary_nutritionist_id AND role_id = 4) INTO v_nut_valid;
        IF NOT v_nut_valid THEN
            RAISE EXCEPTION 'VALIDATION_ERR: El usuario asignado como nutriólogo primario no existe o no tiene el rol de Nutriólogo (role_id = 4).';
        END IF;
    END IF;

    INSERT INTO public.student_clinical_records (student_id, primary_psychologist_id, primary_nutritionist_id, updated_at)
    VALUES (p_student_id, p_primary_psychologist_id, p_primary_nutritionist_id, NOW())
    ON CONFLICT (student_id) DO UPDATE
    SET primary_psychologist_id = coalesce(p_primary_psychologist_id, public.student_clinical_records.primary_psychologist_id),
        primary_nutritionist_id = coalesce(p_primary_nutritionist_id, public.student_clinical_records.primary_nutritionist_id),
        updated_at = NOW();

    INSERT INTO public.audit_logs (user_id, event_type, description, ip_address, created_at)
    VALUES (
        auth.uid(), 
        'ADMIN_ASSIGN_PATIENT', 
        FORMAT('Asignación de paciente %s. Psicólogo: %s, Nutriólogo: %s', p_student_id, coalesce(p_primary_psychologist_id::text, 'Sin cambio'), coalesce(p_primary_nutritionist_id::text, 'Sin cambio')),
        coalesce(current_setting('request.headers', true)::jsonb->>'x-forwarded-for', 'local'),
        NOW()
    );

    v_result := jsonb_build_object(
        'success', true,
        'student_id', p_student_id,
        'primary_psychologist_id', p_primary_psychologist_id,
        'primary_nutritionist_id', p_primary_nutritionist_id,
        'message', 'El paciente ha sido asignado exitosamente a sus especialistas tratantes.'
    );

    RETURN v_result;
END;
$$;


-- =========================================================================================
-- RUTEO DEL ALMACENAMIENTO: MARCA DE AGUA INSTITUCIONAL (SKILL 8.3)
-- =========================================================================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('institutional_assets', 'institutional_assets', true) 
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE POLICY institutional_assets_public_read ON storage.objects 
FOR SELECT USING (bucket_id = 'institutional_assets');

CREATE POLICY institutional_assets_admin_insert ON storage.objects 
FOR INSERT WITH CHECK (
    bucket_id = 'institutional_assets' AND public.get_auth_role() = 1
);

CREATE POLICY institutional_assets_admin_update ON storage.objects 
FOR UPDATE USING (
    bucket_id = 'institutional_assets' AND public.get_auth_role() = 1
);

CREATE POLICY institutional_assets_admin_delete ON storage.objects 
FOR DELETE USING (
    bucket_id = 'institutional_assets' AND public.get_auth_role() = 1
);

-- =========================================================================================
-- CONFIGURACIÓN INSTITUCIONAL (SKILL 8.4)
-- =========================================================================================

CREATE TABLE IF NOT EXISTS public.institutional_settings (
    id SERIAL PRIMARY KEY,
    institution_name TEXT NOT NULL DEFAULT 'BENEMÉRITA UNIVERSIDAD AUTÓNOMA DE PUEBLA',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO public.institutional_settings (id, institution_name) 
VALUES (1, 'BENEMÉRITA UNIVERSIDAD AUTÓNOMA DE PUEBLA') 
ON CONFLICT (id) DO UPDATE SET institution_name = EXCLUDED.institution_name;

ALTER TABLE public.institutional_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY inst_settings_read ON public.institutional_settings FOR SELECT USING (true);
CREATE POLICY inst_settings_insert ON public.institutional_settings FOR INSERT WITH CHECK (public.get_auth_role() = 1);
CREATE POLICY inst_settings_update ON public.institutional_settings FOR UPDATE USING (public.get_auth_role() = 1);

-- =========================================================================================
-- CHAT INTERNO META WHATSAPP (SKILL 11)
-- =========================================================================================

CREATE TABLE public.internal_meta_conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    professional_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    urgency_score DECIMAL(3,2) DEFAULT 0.00,
    last_message TEXT,
    last_message_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    unread_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uniq_student_professional UNIQUE (student_id, professional_id)
);

-- Tabla de Historial de Mensajes de WhatsApp (Bidireccional)
CREATE TABLE public.internal_meta_chats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id UUID NOT NULL REFERENCES public.internal_meta_conversations(id) ON DELETE CASCADE,
    sender_type VARCHAR(50) NOT NULL, -- 'professional' o 'student'
    sender_name TEXT NOT NULL, -- Nombre del emisor
    message_content TEXT NOT NULL, -- Contenido del mensaje
    whatsapp_message_id TEXT UNIQUE, -- ID del mensaje en Meta WhatsApp API (wamid.HBg...)
    status VARCHAR(50) DEFAULT 'sent', -- 'pending', 'sent', 'delivered', 'read', 'failed'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Auditoría y Depuración de Webhooks (Meta WhatsApp Webhooks)
CREATE TABLE public.webhook_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    provider VARCHAR(50) DEFAULT 'whatsapp_meta',
    event_type VARCHAR(100),
    payload JSONB NOT NULL,
    headers JSONB,
    status VARCHAR(50) DEFAULT 'received', -- 'received', 'processed', 'error'
    error_details TEXT,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para Chat Interno Meta
CREATE INDEX idx_internal_meta_conversations_student ON public.internal_meta_conversations(student_id);
CREATE INDEX idx_internal_meta_chats_conversation ON public.internal_meta_chats(conversation_id);
CREATE INDEX idx_internal_meta_chats_wamid ON public.internal_meta_chats(whatsapp_message_id);
CREATE INDEX idx_webhook_logs_created ON public.webhook_logs(created_at);

-- RLS
ALTER TABLE public.internal_meta_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_meta_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad
-- Lectura y gestión de conversaciones: Solo Admins (1) y Clínicos (3, 4)
CREATE POLICY internal_meta_conv_select ON public.internal_meta_conversations
    FOR SELECT TO authenticated USING (
        public.get_auth_role() = 1 OR
        professional_id = auth.uid()
    );

CREATE POLICY internal_meta_conv_all ON public.internal_meta_conversations
    FOR ALL TO authenticated USING (
        public.get_auth_role() = 1 OR
        professional_id = auth.uid()
    );

-- Lectura y gestión de chats: Solo Admins (1) y Clínicos (3, 4)
CREATE POLICY internal_meta_chats_select ON public.internal_meta_chats
    FOR SELECT TO authenticated USING (
        public.get_auth_role() = 1 OR
        EXISTS (
            SELECT 1 FROM public.internal_meta_conversations c
            WHERE c.id = conversation_id AND c.professional_id = auth.uid()
        )
    );

CREATE POLICY internal_meta_chats_all ON public.internal_meta_chats
    FOR ALL TO authenticated USING (
        public.get_auth_role() = 1 OR
        EXISTS (
            SELECT 1 FROM public.internal_meta_conversations c
            WHERE c.id = conversation_id AND c.professional_id = auth.uid()
        )
    );

-- Webhooks: Inserción para servicio, consulta para Admin
CREATE POLICY webhook_logs_insert ON public.webhook_logs
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY webhook_logs_select ON public.webhook_logs
    FOR SELECT TO authenticated USING (public.get_auth_role() = 1);

-- RLS y Políticas para Facultades y Campus
ALTER TABLE public.faculties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campuses ENABLE ROW LEVEL SECURITY;

CREATE POLICY faculties_select ON public.faculties
    FOR SELECT USING (true);

CREATE POLICY faculties_admin_all ON public.faculties
    FOR ALL TO authenticated USING (public.get_auth_role() = 1);

CREATE POLICY campuses_select ON public.campuses
    FOR SELECT USING (true);

CREATE POLICY campuses_admin_all ON public.campuses
    FOR ALL TO authenticated USING (public.get_auth_role() = 1);

CREATE POLICY health_prof_settings_admin_all ON public.health_professional_settings
    FOR ALL TO authenticated USING (public.get_auth_role() = 1);

-- =========================================================================================
-- DERECHOS ARCO (ACCESO, RECTIFICACIÓN, CANCELACIÓN Y OPOSICIÓN)
-- =========================================================================================

-- 1. Tabla para registrar solicitudes formales de Derechos ARCO (Rectificación y Cancelación)
CREATE TABLE IF NOT EXISTS public.arco_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    request_type VARCHAR(20) NOT NULL CHECK (request_type IN ('Access', 'Rectification', 'Cancellation', 'Opposition')),
    details TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Completed')),
    resolution_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 2. Tabla para preferencias de privacidad de Oposición (Derecho de Oposición)
CREATE TABLE IF NOT EXISTS public.user_privacy_settings (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    share_clinical_data BOOLEAN DEFAULT TRUE, -- Oposición a compartir expediente con especialistas asignados
    use_anonymous_stats BOOLEAN DEFAULT TRUE, -- Oposición a uso de datos estadísticos anonimizados
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Habilitar RLS en ambas tablas
ALTER TABLE public.arco_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_privacy_settings ENABLE ROW LEVEL SECURITY;

-- 4. Políticas RLS para arco_requests
CREATE POLICY "Los usuarios pueden ver sus propias solicitudes" 
    ON public.arco_requests FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Los usuarios pueden insertar sus propias solicitudes" 
    ON public.arco_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Solo administradores pueden gestionar solicitudes" 
    ON public.arco_requests FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE public.users.id = auth.uid() AND public.users.role_id = 1
        )
    );

-- 5. Políticas RLS para user_privacy_settings
CREATE POLICY "Los usuarios pueden gestionar sus preferencias de privacidad" 
    ON public.user_privacy_settings FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Solo administradores pueden ver todas las preferencias" 
    ON public.user_privacy_settings FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE public.users.id = auth.uid() AND public.users.role_id = 1
        )
    );

-- 6. Trigger para crear configuración de privacidad por defecto al insertar un nuevo usuario
CREATE OR REPLACE FUNCTION public.handle_new_user_privacy()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.user_privacy_settings (user_id)
    VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created_privacy
    AFTER INSERT ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_privacy();

-- =========================================================================================
-- SISTEMA DE LOGROS, GAMIFICACIÓN Y RACHAS
-- =========================================================================================

-- 1. Tabla de Categorías de Logros
CREATE TABLE IF NOT EXISTS public.achievement_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon_url TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Logros (Catálogo de medallas y metas)
CREATE TABLE IF NOT EXISTS public.achievements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_id UUID REFERENCES public.achievement_categories(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    xp_value INTEGER DEFAULT 10,
    badge_image_url TEXT,
    requirement_type VARCHAR(50), -- Ej. 'diary', 'streak', 'nutrition', 'amati', 'appointment', 'clinical'
    requirement_value INTEGER DEFAULT 1, -- Cantidad requerida para desbloquear el logro
    creator_role VARCHAR(50),
    creator_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Logros de Usuarios (Seguimiento del progreso y medallas obtenidas)
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    achievement_id UUID NOT NULL REFERENCES public.achievements(id) ON DELETE CASCADE,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    progress INTEGER DEFAULT 0, -- Progreso actual hacia el requirement_value
    is_completed BOOLEAN DEFAULT FALSE,
    earned_at TIMESTAMP WITH TIME ZONE,
    awarded_by UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Clínico/Admin que lo otorgó (si fue manual)
    notes TEXT, -- Notas de felicitación o contexto clínico
    UNIQUE(user_id, achievement_id)
);

-- 4. Tabla de Rachas y XP de Usuarios (Streak Engine)
CREATE TABLE IF NOT EXISTS public.user_streaks (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    current_streak INTEGER DEFAULT 0 NOT NULL,
    best_streak INTEGER DEFAULT 0 NOT NULL,
    last_activity_date DATE DEFAULT CURRENT_DATE NOT NULL,
    total_xp INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Habilitar RLS en tablas de logros
ALTER TABLE public.achievement_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_streaks ENABLE ROW LEVEL SECURITY;

-- 6. Índices para Alto Rendimiento
CREATE INDEX IF NOT EXISTS idx_achievements_category ON public.achievements(category_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON public.user_achievements(user_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_achievement ON public.user_achievements(achievement_id);

-- 7. Políticas de Seguridad RLS para Logros
CREATE POLICY achievement_categories_select ON public.achievement_categories
    FOR SELECT TO authenticated USING (true);

CREATE POLICY achievement_categories_modify ON public.achievement_categories
    FOR ALL TO authenticated USING (public.get_auth_role() IN (1, 3, 4));

CREATE POLICY achievements_select ON public.achievements
    FOR SELECT TO authenticated USING (true);

CREATE POLICY achievements_modify ON public.achievements
    FOR ALL TO authenticated USING (public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_achievements_select ON public.user_achievements
    FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_achievements_modify ON public.user_achievements
    FOR ALL TO authenticated USING (public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_streaks_select ON public.user_streaks
    FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_streaks_modify ON public.user_streaks
    FOR ALL TO authenticated USING (true);


-- =========================================================================================
-- EVALUACIONES DE SESIÓN Y ALIANZA TERAPÉUTICA (RUPTURAS)
-- =========================================================================================

-- 1. Tabla de Evaluaciones de Sesión
CREATE TABLE IF NOT EXISTS public.session_evaluations (
  id                        UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id            UUID          NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id                UUID          NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  professional_id           UUID          NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  q1_global               DECIMAL(2,1)  NOT NULL CHECK (q1_global  BETWEEN 1.0 AND 5.0),
  q2_bond                 DECIMAL(2,1)  NOT NULL CHECK (q2_bond    BETWEEN 1.0 AND 5.0),
  q3_goals                DECIMAL(2,1)  NOT NULL CHECK (q3_goals   BETWEEN 1.0 AND 5.0),
  q4_impact               DECIMAL(2,1)  NOT NULL CHECK (q4_impact  BETWEEN 1.0 AND 5.0),
  q5_comment              TEXT,
  score_global            DECIMAL(2,1)  GENERATED ALWAYS AS (
    ROUND(
      (q1_global * 0.20 + q2_bond * 0.30 + q3_goals * 0.25 + q4_impact * 0.25)::numeric,
      1
    )
  ) STORED,
  rupture_flag            TEXT          NOT NULL DEFAULT 'pending' CHECK (rupture_flag IN ('critical', 'decline', 'healthy', 'pending')),
  is_visible_to_professional BOOLEAN   NOT NULL DEFAULT TRUE,
  created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT session_evaluations_appointment_id_unique UNIQUE (appointment_id)
);

-- 2. Índices de Alto Rendimiento para Evaluaciones
CREATE INDEX IF NOT EXISTS idx_session_evaluations_patient_id ON public.session_evaluations (patient_id);
CREATE INDEX IF NOT EXISTS idx_session_evaluations_professional_id ON public.session_evaluations (professional_id);
CREATE INDEX IF NOT EXISTS idx_session_evaluations_created_at ON public.session_evaluations (created_at DESC);

-- 3. Habilitar RLS en Evaluaciones
ALTER TABLE public.session_evaluations ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de Seguridad RLS para Evaluaciones
CREATE POLICY se_patient_insert ON public.session_evaluations
  FOR INSERT TO authenticated WITH CHECK (patient_id = auth.uid());

CREATE POLICY se_patient_select ON public.session_evaluations
  FOR SELECT TO authenticated USING (patient_id = auth.uid());

CREATE POLICY se_professional_select ON public.session_evaluations
  FOR SELECT TO authenticated USING (professional_id = auth.uid() AND is_visible_to_professional = TRUE);

CREATE POLICY se_admin_select ON public.session_evaluations
  FOR SELECT TO authenticated USING (public.get_auth_role() = 1);

-- 5. Función compute_rupture_flag
CREATE OR REPLACE FUNCTION public.compute_rupture_flag(
  p_q1_global    DECIMAL(2,1),
  p_q2_bond      DECIMAL(2,1),
  p_q3_goals     DECIMAL(2,1),
  p_q4_impact    DECIMAL(2,1),
  p_score_global DECIMAL(2,1)
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
AS $$
DECLARE
  v_has_critical_dimension BOOLEAN;
  v_all_dimensions_healthy BOOLEAN;
END;
$$;

-- Implementación interna de la lógica de ruptura terapéutica
CREATE OR REPLACE FUNCTION public.compute_rupture_flag(
  p_q1_global    DECIMAL(2,1),
  p_q2_bond      DECIMAL(2,1),
  p_q3_goals     DECIMAL(2,1),
  p_q4_impact    DECIMAL(2,1),
  p_score_global DECIMAL(2,1)
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
AS $$
DECLARE
  v_has_critical_dimension BOOLEAN;
  v_all_dimensions_healthy BOOLEAN;
BEGIN
  v_has_critical_dimension := (
    p_q1_global <= 2.0 OR
    p_q2_bond   <= 2.0 OR
    p_q3_goals  <= 2.0 OR
    p_q4_impact <= 2.0
  );

  v_all_dimensions_healthy := (
    p_q1_global >= 3.0 AND
    p_q2_bond   >= 3.0 AND
    p_q3_goals  >= 3.0 AND
    p_q4_impact >= 3.0
  );

  IF v_has_critical_dimension OR p_score_global < 3.5 THEN
    RETURN 'critical';
  END IF;

  IF p_score_global >= 4.0 AND v_all_dimensions_healthy THEN
    RETURN 'healthy';
  END IF;

  RETURN 'decline';
END;
$$;

-- 6. Función de Trigger trg_set_rupture_flag
CREATE OR REPLACE FUNCTION public.fn_set_rupture_flag()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_score_global DECIMAL(2,1);
BEGIN
  v_score_global := ROUND(
    (
      NEW.q1_global * 0.20 +
      NEW.q2_bond   * 0.30 +
      NEW.q3_goals  * 0.25 +
      NEW.q4_impact * 0.25
    )::numeric,
    1
  );

  NEW.rupture_flag := public.compute_rupture_flag(
    NEW.q1_global,
    NEW.q2_bond,
    NEW.q3_goals,
    NEW.q4_impact,
    v_score_global
  );

  RETURN NEW;
END;
$$;

-- 7. Registro de Trigger en session_evaluations
CREATE TRIGGER trg_set_rupture_flag
  BEFORE INSERT
  ON public.session_evaluations
);

-- 4. Tabla de Rachas y XP de Usuarios (Streak Engine)
CREATE TABLE IF NOT EXISTS public.user_streaks (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    current_streak INTEGER DEFAULT 0 NOT NULL,
    best_streak INTEGER DEFAULT 0 NOT NULL,
    last_activity_date DATE DEFAULT CURRENT_DATE NOT NULL,
    total_xp INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Habilitar RLS en tablas de logros
ALTER TABLE public.achievement_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_streaks ENABLE ROW LEVEL SECURITY;

-- 6. Índices para Alto Rendimiento
CREATE INDEX IF NOT EXISTS idx_achievements_category ON public.achievements(category_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON public.user_achievements(user_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_achievement ON public.user_achievements(achievement_id);

-- 7. Políticas de Seguridad RLS para Logros
CREATE POLICY achievement_categories_select ON public.achievement_categories
    FOR SELECT TO authenticated USING (true);

CREATE POLICY achievement_categories_modify ON public.achievement_categories
    FOR ALL TO authenticated USING (public.get_auth_role() IN (1, 3, 4));

CREATE POLICY achievements_select ON public.achievements
    FOR SELECT TO authenticated USING (true);

CREATE POLICY achievements_modify ON public.achievements
    FOR ALL TO authenticated USING (public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_achievements_select ON public.user_achievements
    FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_achievements_modify ON public.user_achievements
    FOR ALL TO authenticated USING (public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_streaks_select ON public.user_streaks
    FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.get_auth_role() IN (1, 3, 4));

CREATE POLICY user_streaks_modify ON public.user_streaks
    FOR ALL TO authenticated USING (true);


-- =========================================================================================
-- EVALUACIONES DE SESIÓN Y ALIANZA TERAPÉUTICA (RUPTURAS)
-- =========================================================================================

-- 1. Tabla de Evaluaciones de Sesión
CREATE TABLE IF NOT EXISTS public.session_evaluations (
  id                        UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id            UUID          NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id                UUID          NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  professional_id           UUID          NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  q1_global               DECIMAL(2,1)  NOT NULL CHECK (q1_global  BETWEEN 1.0 AND 5.0),
  q2_bond                 DECIMAL(2,1)  NOT NULL CHECK (q2_bond    BETWEEN 1.0 AND 5.0),
  q3_goals                DECIMAL(2,1)  NOT NULL CHECK (q3_goals   BETWEEN 1.0 AND 5.0),
  q4_impact               DECIMAL(2,1)  NOT NULL CHECK (q4_impact  BETWEEN 1.0 AND 5.0),
  q5_comment              TEXT,
  score_global            DECIMAL(2,1)  GENERATED ALWAYS AS (
    ROUND(
      (q1_global * 0.20 + q2_bond * 0.30 + q3_goals * 0.25 + q4_impact * 0.25)::numeric,
      1
    )
  ) STORED,
  rupture_flag            TEXT          NOT NULL DEFAULT 'pending' CHECK (rupture_flag IN ('critical', 'decline', 'healthy', 'pending')),
  is_visible_to_professional BOOLEAN   NOT NULL DEFAULT TRUE,
  created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT session_evaluations_appointment_id_unique UNIQUE (appointment_id)
);

-- 2. Índices de Alto Rendimiento para Evaluaciones
CREATE INDEX IF NOT EXISTS idx_session_evaluations_patient_id ON public.session_evaluations (patient_id);
CREATE INDEX IF NOT EXISTS idx_session_evaluations_professional_id ON public.session_evaluations (professional_id);
CREATE INDEX IF NOT EXISTS idx_session_evaluations_created_at ON public.session_evaluations (created_at DESC);

-- 3. Habilitar RLS en Evaluaciones
ALTER TABLE public.session_evaluations ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de Seguridad RLS para Evaluaciones
CREATE POLICY se_patient_insert ON public.session_evaluations
  FOR INSERT TO authenticated WITH CHECK (patient_id = auth.uid());

CREATE POLICY se_patient_select ON public.session_evaluations
  FOR SELECT TO authenticated USING (patient_id = auth.uid());

CREATE POLICY se_professional_select ON public.session_evaluations
  FOR SELECT TO authenticated USING (professional_id = auth.uid() AND is_visible_to_professional = TRUE);

CREATE POLICY se_admin_select ON public.session_evaluations
  FOR SELECT TO authenticated USING (public.get_auth_role() = 1);

-- 5. Función compute_rupture_flag
CREATE OR REPLACE FUNCTION public.compute_rupture_flag(
  p_q1_global    DECIMAL(2,1),
  p_q2_bond      DECIMAL(2,1),
  p_q3_goals     DECIMAL(2,1),
  p_q4_impact    DECIMAL(2,1),
  p_score_global DECIMAL(2,1)
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
AS $$
DECLARE
  v_has_critical_dimension BOOLEAN;
  v_all_dimensions_healthy BOOLEAN;
END;
$$;

-- Implementación interna de la lógica de ruptura terapéutica
CREATE OR REPLACE FUNCTION public.compute_rupture_flag(
  p_q1_global    DECIMAL(2,1),
  p_q2_bond      DECIMAL(2,1),
  p_q3_goals     DECIMAL(2,1),
  p_q4_impact    DECIMAL(2,1),
  p_score_global DECIMAL(2,1)
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
AS $$
DECLARE
  v_has_critical_dimension BOOLEAN;
  v_all_dimensions_healthy BOOLEAN;
BEGIN
  v_has_critical_dimension := (
    p_q1_global <= 2.0 OR
    p_q2_bond   <= 2.0 OR
    p_q3_goals  <= 2.0 OR
    p_q4_impact <= 2.0
  );

  v_all_dimensions_healthy := (
    p_q1_global >= 3.0 AND
    p_q2_bond   >= 3.0 AND
    p_q3_goals  >= 3.0 AND
    p_q4_impact >= 3.0
  );

  IF v_has_critical_dimension OR p_score_global < 3.5 THEN
    RETURN 'critical';
  END IF;

  IF p_score_global >= 4.0 AND v_all_dimensions_healthy THEN
    RETURN 'healthy';
  END IF;

  RETURN 'decline';
END;
$$;

-- 6. Función de Trigger trg_set_rupture_flag
CREATE OR REPLACE FUNCTION public.fn_set_rupture_flag()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_score_global DECIMAL(2,1);
BEGIN
  v_score_global := ROUND(
    (
      NEW.q1_global * 0.20 +
      NEW.q2_bond   * 0.30 +
      NEW.q3_goals  * 0.25 +
      NEW.q4_impact * 0.25
    )::numeric,
    1
  );

  NEW.rupture_flag := public.compute_rupture_flag(
    NEW.q1_global,
    NEW.q2_bond,
    NEW.q3_goals,
    NEW.q4_impact,
    v_score_global
  );

  RETURN NEW;
END;
$$;

-- 7. Registro de Trigger en session_evaluations
CREATE TRIGGER trg_set_rupture_flag
  BEFORE INSERT
  ON public.session_evaluations
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_set_rupture_flag();


-- =========================================================================================
-- MOTOR DE RACHAS: FUNCIÓN PostgreSQL ALMACENADA (STREAK ENGINE)
-- =========================================================================================
CREATE OR REPLACE FUNCTION public.update_user_activity_streak(
    p_user_id UUID,
    p_category TEXT -- 'diary', 'nutrition', 'amati', 'appointment'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_streak        user_streaks%ROWTYPE;
  v_today         date := current_date;
  v_new_streak    int := 1;
  v_xp_gain       int := 10;
  v_unlocked      jsonb := '[]'::jsonb;
  v_ach           record;
  v_count         int;
BEGIN
  -- ─── 1. Obtener o crear la racha del usuario ───────────────────────────
  SELECT * INTO v_streak
  FROM user_streaks
  WHERE user_id = p_user_id;

  IF NOT FOUND THEN
    INSERT INTO user_streaks (user_id, current_streak, best_streak, last_activity_date, total_xp)
    VALUES (p_user_id, 1, 1, v_today, v_xp_gain)
    RETURNING * INTO v_streak;
  ELSE
    IF v_streak.last_activity_date = v_today THEN
      v_new_streak := v_streak.current_streak;  -- Ya registró hoy
    ELSIF v_streak.last_activity_date = v_today - INTERVAL '1 day' THEN
      v_new_streak := v_streak.current_streak + 1;  -- Consecutivo
    ELSE
      v_new_streak := 1;  -- Racha rota
    END IF;

    UPDATE user_streaks
    SET
      current_streak     = v_new_streak,
      best_streak        = GREATEST(best_streak, v_new_streak),
      last_activity_date = v_today,
      total_xp           = total_xp + v_xp_gain
    WHERE user_id = p_user_id
    RETURNING * INTO v_streak;
  END IF;

  -- ─── 2. Evaluar logros de esta categoría ──────────────────────────────
  FOR v_ach IN
    SELECT a.id, a.title, a.xp_value, a.requirement_type, a.requirement_value
    FROM achievements a
    WHERE a.requirement_type = p_category
      AND NOT EXISTS (
        SELECT 1 FROM user_achievements ua
        WHERE ua.achievement_id = a.id
          AND ua.user_id = p_user_id
          AND ua.is_completed = true
      )
  LOOP
    v_count := 0;

    CASE v_ach.requirement_type
      WHEN 'diary' THEN
        SELECT COUNT(*) INTO v_count
        FROM diary_entries WHERE student_id = p_user_id;

      WHEN 'nutrition' THEN
        SELECT COUNT(*) INTO v_count
        FROM food_diary_entries WHERE student_id = p_user_id;

      WHEN 'streak' THEN
        v_count := v_streak.current_streak;

      WHEN 'amati' THEN
        SELECT COUNT(*) INTO v_count
        FROM chats WHERE student_id = p_user_id;

      WHEN 'appointment' THEN
        SELECT COUNT(*) INTO v_count
        FROM appointments
        WHERE student_id = p_user_id AND status = 'completed';

      ELSE
        v_count := 0;
    END CASE;

    IF v_count >= v_ach.requirement_value THEN
      -- Desbloquear logro
      INSERT INTO user_achievements (user_id, achievement_id, progress, is_completed, earned_at)
      VALUES (p_user_id, v_ach.id, v_count, true, now())
      ON CONFLICT (user_id, achievement_id) DO UPDATE
        SET progress     = EXCLUDED.progress,
            is_completed = true,
            earned_at    = COALESCE(user_achievements.earned_at, now())
      WHERE user_achievements.is_completed = false;

      -- Si se desbloqueó recién (was false, now true)
      IF FOUND THEN
        v_unlocked := v_unlocked || jsonb_build_object(
          'id',       v_ach.id,
          'title',    v_ach.title,
          'xp_value', v_ach.xp_value
        );
        UPDATE user_streaks
        SET total_xp = total_xp + v_ach.xp_value
        WHERE user_id = p_user_id;
      END IF;
    ELSE
      -- Solo actualizar progreso
      INSERT INTO user_achievements (user_id, achievement_id, progress, is_completed)
      VALUES (p_user_id, v_ach.id, v_count, false)
      ON CONFLICT (user_id, achievement_id) DO UPDATE
        SET progress = GREATEST(user_achievements.progress, EXCLUDED.progress)
      WHERE user_achievements.is_completed = false;
    END IF;
  END LOOP;

  -- ─── 3. Leer estado actualizado ───────────────────────────────────────
  SELECT * INTO v_streak FROM user_streaks WHERE user_id = p_user_id;

  RETURN jsonb_build_object(
    'current_streak',        v_streak.current_streak,
    'best_streak',           v_streak.best_streak,
    'total_xp',              v_streak.total_xp,
    'unlocked_achievements', v_unlocked
  );

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING '[update_user_activity_streak] %: %', SQLERRM, SQLSTATE;
  RETURN jsonb_build_object(
    'error',                 SQLERRM,
    'current_streak',        0,
    'total_xp',              0,
    'unlocked_achievements', '[]'::jsonb
  );
END;
$$;
