-- =========================================================================================
-- EXTENSIONES
-- =========================================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================================
-- ROLES
-- =========================================================================================
CREATE TABLE public.roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO public.roles (id, name) VALUES 
  (1, 'Admin'),
  (2, 'Estudiante'),
  (3, 'Psicologo'),
  (4, 'Nutricionista')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

SELECT setval('public.roles_id_seq', 4, true);

-- =========================================================================================
-- USUARIOS
-- =========================================================================================
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    matricula VARCHAR(50) UNIQUE NOT NULL,
    role_id INTEGER REFERENCES public.roles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- PERFILES
-- =========================================================================================
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    avatar_url TEXT,
    UNIQUE(user_id)
);

-- =========================================================================================
-- CAMPUS & FACULTADES
-- =========================================================================================
CREATE TABLE public.campuses (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.faculties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id INTEGER REFERENCES public.campuses(id) ON DELETE CASCADE,
    name TEXT UNIQUE NOT NULL,
    virtual_tour_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- CLÍNICO
-- =========================================================================================
CREATE TABLE public.student_clinical_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    primary_psychologist_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    primary_nutritionist_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    known_conditions TEXT[] DEFAULT '{}',
    consent_given BOOLEAN DEFAULT FALSE,
    additional_notes TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id)
);

CREATE TABLE public.patient_settings (
    student_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'active',
    self_diagnosis VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- CHAT
-- =========================================================================================
CREATE TABLE public.chats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT,
    status VARCHAR(20) DEFAULT 'active',
    highest_urgency_score DECIMAL(3,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    chat_id UUID REFERENCES public.chats(id) ON DELETE CASCADE,
    sender_type VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    urgency_score DECIMAL(3,2),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- AGENDA
-- =========================================================================================
CREATE TABLE public.appointments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    psychologist_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    scheduled_date TIMESTAMP NOT NULL,
    priority_level VARCHAR(20) DEFAULT 'Routine',
    status VARCHAR(20) DEFAULT 'Scheduled',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.psychologist_settings (
    psychologist_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    session_duration INTEGER DEFAULT 50,
    capacity INTEGER DEFAULT 35,
    faculty_id BIGINT REFERENCES public.faculties(id),
    building TEXT,
    office_room TEXT,
    working_days JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.psychologist_exceptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    psychologist_id UUID REFERENCES public.users(id),
    exception_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- NUTRICIÓN
-- =========================================================================================
CREATE TABLE public.nutrition_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    log_date DATE DEFAULT CURRENT_DATE,
    total_calories INTEGER DEFAULT 0,
    total_protein DECIMAL(5,2) DEFAULT 0,
    total_carbs DECIMAL(5,2) DEFAULT 0,
    total_fats DECIMAL(5,2) DEFAULT 0,
    UNIQUE(student_id, log_date)
);

CREATE TABLE public.food_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nutrition_log_id UUID REFERENCES public.nutrition_logs(id) ON DELETE CASCADE,
    meal_type VARCHAR(50),
    name TEXT,
    calories INTEGER,
    protein DECIMAL(5,2),
    carbs DECIMAL(5,2),
    fats DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- DIARIO
-- =========================================================================================
CREATE TABLE public.diary_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    content TEXT,
    moods TEXT[],
    high_risk BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- AUDITORÍA
-- =========================================================================================
CREATE TABLE public.audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID,
    event_type TEXT,
    description TEXT,
    ip_address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================================
-- FUNCIÓN DE ROL (SEGURA)
-- =========================================================================================
CREATE OR REPLACE FUNCTION public.get_auth_role()
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT COALESCE(
    (SELECT role_id FROM public.users WHERE id = auth.uid()),
    0
  );
$$;

-- =========================================================================================
-- RLS
-- =========================================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diary_entries ENABLE ROW LEVEL SECURITY;

-- Usuarios
CREATE POLICY user_own_data ON public.users
FOR ALL USING (id = auth.uid())
WITH CHECK (id = auth.uid());

CREATE POLICY profile_own_data ON public.profiles
FOR ALL USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Chat
CREATE POLICY chat_own ON public.chats
FOR ALL USING (student_id = auth.uid())
WITH CHECK (student_id = auth.uid());

CREATE POLICY message_own ON public.messages
FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.chats c 
        WHERE c.id = chat_id AND c.student_id = auth.uid()
    )
);

-- Diario
CREATE POLICY diary_own ON public.diary_entries
FOR ALL USING (student_id = auth.uid())
WITH CHECK (student_id = auth.uid());

-- =========================================================================================
-- ÍNDICES
-- =========================================================================================
CREATE INDEX idx_chats_student ON public.chats(student_id);
CREATE INDEX idx_messages_chat ON public.messages(chat_id);
CREATE INDEX idx_appointments_psy ON public.appointments(psychologist_id);
CREATE INDEX idx_diary_student ON public.diary_entries(student_id);
CREATE INDEX idx_nutrition_logs ON public.nutrition_logs(student_id, log_date);
